name              'firefox'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs Mozilla Firefox on multiple operating systems'
version           '6.0.0'
source_url        'https://github.com/sous-chefs/firefox'
issues_url        'https://github.com/sous-chefs/firefox/issues'
chef_version      '>= 14'

supports 'centos'
supports 'debian'
supports 'mac_os_x'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
supports 'windows'
