name              'firefox'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Installs Mozilla Firefox on multiple operating systems'
version           '7.0.0'
source_url        'https://github.com/sous-chefs/firefox'
issues_url        'https://github.com/sous-chefs/firefox/issues'
chef_version      '>= 15.3'

supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'mac_os_x', '>= 10.15'
supports 'opensuseleap', '>= 16.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'ubuntu', '>= 22.04'
supports 'windows', '>= 10.0'
